
def create_tables() -> str:
    # DROP TABLE IF EXISTS BANK_DATA;
    # DROP INDEX IF EXISTS INDEX_ACCOUNT;
    return """
    BEGIN;

    CREATE TABLE IF NOT EXISTS BANK_DATA (
        ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
        NAME TEXT NOT NULL,
        ACCOUNT TEXT NOT NULL UNIQUE,
        BALANCE NUMERIC NOT NULL,
        TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE UNIQUE INDEX IF NOT EXISTS INDEX_ACCOUNT ON BANK_DATA (ACCOUNT);

    COMMIT;
    """